(load "2-7.scm")
(load "2-8.scm")
(define (make-center-width c w)
  (make-interval (- c w) (+ c w))
)

(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2.0)
)

(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2.0)
)

(define (make-center-percent center percent)
   (let ((width (abs (* center percent))))
   	(make-center-width center width)
   )
)

(define (percent i)
  (let ((c (abs (center i)))
  	    (w (width i)))
  	(/ w c)
  )
)

(define (display-center-percent i)
  (newline)
  (display "[")
  (display (center i))
  (display ",")
  (display (percent i))
  (display "]")
)