(define (deep-reverse items)
	(define (rev-iter things result)
		(cond ((null? things) result)
		      ((not (pair? things)) things)
			  (else	(rev-iter (cdr things) 
			  		(cons (rev-iter (car things) '()) result))
			  )
		)
	)
	(rev-iter items '())
)