(load "2-2.scm")
(define (perimeter-rectangle r)
  (let ((leng (length-of-rectangle r))
        (wid (width-of-rectangle r)))
  	(* 2 (+ leng wid))
  )
)

(define (area-rectangle r)
  (* (length-of-rectangle r) (width-of-rectangle r))
)

(define (make-rectangle leng wid)
  (cons leng wid)
)

(define (length-rectangle r)
  (car r)	
)

(define (width-rectangle r)
  (cdr r)
)

(define (length-of-rectangle r)
  (let ((leng (length-rectangle r)))
  	(let ((start (start-segment leng))
  		  (end (end-segment leng))
  		 )
  		 (- (x-point end) (x-point start)) 
  	)
  )
)

(define (width-of-rectangle r)
  (let ((wid (width-rectangle r)))
  	(let ((start (start-segment wid))
  	      (end (end-segment wid)))
  		(- (y-point end) (y-point start))
  	)
  )
)