(load "2-67.scm")

(define (encode message tree)
  (define (encode-symbol symbol tree)
    (cond ((not (memq symbol (symbols tree))) (error "error symbol" symbol))
          ((leaf? tree) '())
          ((memq symbol (symbols (left-branch tree)))
          		(cons '0 (encode-symbol symbol (left-branch tree))))
          ((memq symbol (symbols (right-branch tree)))
          		(cons '1 (encode-symbol symbol (right-branch tree))))
    )
  )

  (if (null? message)
      '()
      (append (encode-symbol (car message) tree)
      		  (encode (cdr message) tree))
  )
)