(load "2-67.scm")
(load "2-68.scm")

(define (generate-huffman-tree pairs)
   (define (successive-merge leaves)
     (if (= 1 (length leaves))
         (car leaves)
         (let ((first (car leaves))
         	   (second (cadr leaves))
         	   (rest (cddr leaves))
         	  )
         	(successive-merge (adjoin-set (make-code-tree first second) rest))
         )
     )
   )
   (successive-merge (make-leaf-set pairs))
)