(load "2-7.scm")

(define (sub-interval x y)
  	(make-interval (- (lower-bound x) (upper-bound y)) 
  				   (- (upper-bound x) (lower-bound y)))
)

(define (display-interval x)
  (newline)
  (display "[")
  (display (lower-bound x))
  (display ",")
  (display (upper-bound x))
  (display "]")
)