(define (make-account balance password)
  (let ((times 0))
    (define (call-the-cops m)
      "Call the cops!!!"
    )
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
        	       balance)
          "Insufficient funds")
    )
    (define (deposit amount)
      (set! balance (+ balance amount))
	  balance)
    (define (dispatch p op)
      (cond ((not (eq? p password)) (begin (set! times (+ times 1)) 
                                           (if (>= times 7)
                                               call-the-cops
                                               (lambda (m) "Wrong password"))))
    	      ((eq? op 'withdraw) withdraw)
            ((eq? op 'deposit) deposit)
      	    (else (error "Unknow-request -- MAKE-ACCOUNT"))))
      dispatch)
)